server:
  port: 9002

spring:  application:    name: nacos-payment-provider
  cloud:    nacos:      discovery:        server-addr: 192.168.1.110:8848,192.168.1.111:8848,192.168.1.112:8848
  
management:
   endpoints:
       web:
         exposure:
          include: "*"
          
      