server:
  port: 8401

spring:  application:    name: cloudalibaba-sentinel-service
  cloud:    nacos:      config:        server-addr: 192.168.1.110:8848,192.168.1.111:8848,192.168.1.112:8848
      discovery:        server-addr: 192.168.1.110:8848,192.168.1.111:8848,192.168.1.112:8848  
    sentinel:      transport:        dashboard: localhost:8080  #sentinel 控制台地址
        port: 8719    #如果8080端口被占用  从8719开始一次加1扫描，直到端口不被占用
      datasource:        ds1:
          nacos:
            server-addr: 192.168.1.110:8848,192.168.1.111:8848,192.168.1.112:8848
            data-id: ${spring.application.name}
            data-type: json
            rule-type: flow
            group-id: DEFAULT_GROUP
        
            
management:
   endpoints:
       web:
         exposure:
          include: "*"