server:
  port: 83

spring:  application:    name: nacos-order-consumer
  cloud:    nacos:      discovery:        server-addr: 192.168.1.110:8848,192.168.1.111:8848,192.168.1.112:8848

management:
   endpoints:
       web:
         exposure:
          include: "*"
          
serverApi:
  paymentServer: http://nacos-payment-provider      